spring.application.name=UserService

server.port=8081

spring.datasource.url=jdbc:mariadb://localhost:3306/user_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

## B?t giao di?n console H2 (http://localhost:8081/h2-console)
#spring.h2.console.enabled=true

# --- JPA / HIBERNATE ---
# T? ??ng t?o b?ng t? @Entity
spring.jpa.hibernate.ddl-auto=update
# Hi?n th? SQL trong log
spring.jpa.show-sql=true
# --- CH?Y FILE data.sql T? ??NG ---
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# --- KAFKA ---
spring.kafka.bootstrap-servers=172.27.98.64:9092
# Ép Kafka dùng b? chuy?n ??i JSON cho Object
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer