spring.config.import=optional:file:.env[.properties]
spring.application.name=user-service
server.port=${USER_SERVICE_PORT}
spring.datasource.url=jdbc:mariadb://mariadb-may2:3306/user_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.sql.init.mode=always
spring.kafka.bootstrap-servers=${IP_MAY1}:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
