services:
  mariadb-may3:
    image: mariadb:10.11
    container_name: mariadb-may3
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: payment_db
    volumes:
      - mariadb_data_may3:/var/lib/mysql

  payment-service:
    build: ./PaymentService
    container_name: payment-service
    ports:
      - "${PAYMENT_SERVICE_PORT}:${PAYMENT_SERVICE_PORT}"
    env_file: .env
    depends_on:
      - mariadb-may3
    volumes:
      - ./.env:/app/.env

volumes:
  mariadb_data_may3:
