services:
  # --- HẠ TẦNG (KAFKA & ZOOKEEPER) ---
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # --- DATABASE DÙNG CHUNG ---
  mariadb:
    image: mariadb:10.11
    container_name: mariadb-all
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: user_db 
    volumes:
      - mariadb_data_all:/var/lib/mysql

  # --- MICROSERVICES ---
  gateway-service:
    build: ./GatewayService
    container_name: gateway-service
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    env_file: .env
    environment:
      - IP_MAY1=host.docker.internal
      - IP_MAY2=host.docker.internal
      - IP_MAY3=host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - kafka

  user-service:
    build: ./UserService
    container_name: user-service
    ports:
      - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"
    env_file: .env
    environment:
      - IP_MAY1=host.docker.internal
      - IP_MAY2=host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mariadb
      - kafka

  movie-service:
    build: ./MovieService
    container_name: movie-service
    ports:
      - "${MOVIE_SERVICE_PORT}:${MOVIE_SERVICE_PORT}"
    env_file: .env
    environment:
      - IP_MAY1=host.docker.internal
      - IP_MAY2=host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mariadb
      - kafka

  booking-service:
    build: ./BookingService
    container_name: booking-service
    ports:
      - "${BOOKING_SERVICE_PORT}:${BOOKING_SERVICE_PORT}"
    env_file: .env
    environment:
      - IP_MAY1=host.docker.internal
      - IP_MAY2=host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mariadb
      - kafka

  payment-service:
    build: ./PaymentService
    container_name: payment-service
    ports:
      - "${PAYMENT_SERVICE_PORT}:${PAYMENT_SERVICE_PORT}"
    env_file: .env
    environment:
      - IP_MAY1=host.docker.internal
      - IP_MAY3=host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mariadb
      - kafka

  # --- FRONTEND ---
  frontend:
    build:
      context: ./FE
      args:
        - VITE_GATEWAY_URL=http://127.0.0.1:${GATEWAY_PORT}
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - gateway-service

volumes:
  mariadb_data_all:
