spring.application.name=PaymentService
server.port=8084

# C?u hình Kafka
spring.kafka.bootstrap-servers=192.168.137.129:9092
spring.kafka.consumer.group-id=payment-group

# 1. Báo cho Kafka bi?t Value nh?n v? ph?i ???c d?ch sang JSON (Map/Object)
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# 2. C?c k? quan tr?ng: Cho phép d?ch t?t c? các package và map th?ng ra java.util.Map
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.value.default.type=java.util.Map

# (Tùy ch?n) N?u Payment c?ng g?i event tr? l?i thì c?u hình luôn Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer