spring.config.import=optional:file:.env[.properties]
spring.application.name=movie-service
server.port=${MOVIE_SERVICE_PORT}
spring.datasource.url=jdbc:mariadb://${IP_MAY2}:3306/movie_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.kafka.bootstrap-servers=${IP_MAY1}:9092
