spring.config.import=optional:file:.env[.properties]
spring.application.name=movie-service
server.port=${MOVIE_SERVICE_PORT}
spring.datasource.url=jdbc:mariadb://mariadb-may2:3306/movie_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.sql.init.mode=always
spring.kafka.bootstrap-servers=${IP_MAY1}:9092
