spring.application.name=MovieService
server.port=8082

# H2 Database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driverClassName=org.h2.Driver

# Ép n?p data.sql sau khi Hibernate t?o b?ng
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Log ?? b?t t?n tay n?u SQL l?i
logging.level.org.springframework.jdbc.datasource.init=DEBUG
spring.jpa.show-sql=true