server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Proxy các request API nếu cần (tùy chọn, vì FE gọi trực tiếp Gateway)
    # location /api {
    #     proxy_pass http://172.20.37.178:8080;
    # }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
